class Autogenerated {
  String code;
  String message;
  List<Data> data;

  Autogenerated({this.code, this.message, this.data});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    var data;
    if (json['data'] != null) {
      data = List<Data>();
      json['data'].forEach((v) {
        data.add(Data.fromJson(v));
      });
    }
    return Autogenerated(
        code: json['code'], message: json['message'], data: data);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String image;
  double oriPrice;
  double presentPrice;
  String goodsName;
  String goodsId;

  Data(
      {this.image,
      this.oriPrice,
      this.presentPrice,
      this.goodsName,
      this.goodsId});

  factory Data.fromJson(Map<String, dynamic> json) {
    return Data(
        image: json['image'],
        oriPrice: json['oriPrice'],
        presentPrice: json['presentPrice'],
        goodsName: json['goodsName'],
        goodsId: json['goodsId']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['image'] = this.image;
    data['oriPrice'] = this.oriPrice;
    data['presentPrice'] = this.presentPrice;
    data['goodsName'] = this.goodsName;
    data['goodsId'] = this.goodsId;
    return data;
  }
}
